# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        GH_KEY: ${{ secrets.GH_KEY }}
    - run: npm ci
    - run: npm run build --if-present
    - run: cp -r ./public/** ./
    - run: git config --global user.name "goransle"
    - run: git config --global user.email "goransle@gmail.com"
    - run: git fetch origin
    - run: git checkout gh-pages
    - run: git add . && git commit -m "latest fresh release from the robot shop"
    - run: echo $GH_KEY | git push -u origin gh-pages
